kind: Service
apiVersion: v1
metadata:
  #Service name
  name: randomforest
spec:
  selector:
    app: cloudmesh-282704
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
